#Basprofil
server:
  port: 8081

spring:
  application:
    name: Wigell Cinema mikrotjänst
  profiles:
    active: prod

logging:
  level:
    root: info

management:
  server:
    port: 6080
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Wigell Cinema mikrotjänst
    version: 1.0.0
    description: Wigell Cinema mikrotjänst i grupparbetet i kursen Java Backend HT 2025

---
#Utvecklingsprofil (dev)
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:cinemaDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info, metrics, loggers, mappings

---
#Produktionsprofil (prod)
spring:
  config:
    activate:
      on-profile: prod
  boot:
    admin:
      client:
        url: http://localhost:9090
        username: admin
        password: admin
        instance:
          management-base-url: http://localhost:6081
  datasource:
    url: jdbc:mysql://localhost:3306/wigell_cinema_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8583

management:
  endpoints:
    web:
      exposure:
        include: health,info